-- 避免中文亂碼
-- ref. https://blog.csdn.net/qq_27331631/article/details/109271634
-- ref. https://www.itread01.com/lefix.html
CREATE DATABASE DB_EMP_DEPT COLLATE Chinese_PRC_CI_AS;

USE DB_EMP_DEPT;
----------------------------------------------------
-- DROP TABLE EMP_TB;
-- DROP TABLE DEPT_TB;
----------------------------------------------------

CREATE TABLE DEPT_TB
(
    DEPTNO	INT IDENTITY(10,10) PRIMARY KEY NOT NULL,
    DNAME	VARCHAR(14),
    LOC		VARCHAR(13)
);

CREATE TABLE EMP_TB
(
    EMPNO	 INT IDENTITY(7001,1) PRIMARY KEY not null,
    ename	 VARCHAR(14),
    job		 VARCHAR(13),
    HIREDATE  DATE,
    DEPTNO INT NOT NULL FOREIGN KEY REFERENCES DEPT_TB(DEPTNO)
    --Hibernate 做關聯查詢其實可以不用在實體表格設定 foreign-key
);

INSERT INTO DEPT_TB VALUES ('財務部','臺灣台北');
INSERT INTO DEPT_TB VALUES ('研發部','臺灣新竹');
INSERT INTO DEPT_TB VALUES ('業務部','美國紐約');
INSERT INTO DEPT_TB VALUES ('生管部','中國上海');

INSERT INTO EMP_TB VALUES ('KING','PRESIDENT','1981-11-17',10);
INSERT INTO EMP_TB VALUES ('BLAKE','MANAGER','1981-05-01',30);
INSERT INTO EMP_TB VALUES ('CLARK','MANAGER','1981-01-09',10);
INSERT INTO EMP_TB VALUES ('JONES','MANAGER','1981-04-02',20);
INSERT INTO EMP_TB VALUES ('MARTIN','SALESMAN','1981-09-28',30);
INSERT INTO EMP_TB VALUES ('ALLEN','SALESMAN','1981-02-2',30);
INSERT INTO EMP_TB VALUES ('TURNER','SALESMAN','1981-09-28',30);
INSERT INTO EMP_TB VALUES ('JAMES','CLERK','1981-12-03',30);
INSERT INTO EMP_TB VALUES ('WARD','SALESMAN','1981-02-22',30);
INSERT INTO EMP_TB VALUES ('FORD','ANALYST','1981-12-03',20);
INSERT INTO EMP_TB VALUES ('SMITH','CLERK','1980-12-17',20);
INSERT INTO EMP_TB VALUES ('SCOTT','ANALYST','1981-12-09',20);
INSERT INTO EMP_TB VALUES ('ADAMS','CLERK','1983-01-12',20);
INSERT INTO EMP_TB VALUES ('MILLER','CLERK','1982-01-23',10);

--UPDATE dbo.dept_TB SET dname='數位金融部',loc='B棟18樓' WHERE deptno=90;
--DELETE FROM dbo.dept_TB WHERE deptno=60;